// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuxus.Backend;

#nullable disable

namespace Nuxus.Backend.Migrations
{
    [DbContext(typeof(NuxusDbContext))]
    partial class NuxusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");

            modelBuilder.Entity("Nuxus.Server.ApiKey", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("KeyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("KeyName");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Hash");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Salt");

                    b.HasKey("UserId", "KeyName");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Nuxus.Server.Package", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("Version");

                    b.PrimitiveCollection<string>("TargetFrameworks")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetFrameworks");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("UploadTime");

                    b.Property<Guid>("UploadUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UploadUserId");

                    b.HasKey("Name", "Version");

                    b.ToTable("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
